{"name": "Проверяем что невозможно авторизоваться при отправке некорректных данных.", "status": "passed", "steps": [{"name": "Авторизация курьера", "status": "passed", "parameters": [{"name": "login", "value": "'incorrect_data'"}, {"name": "password", "value": "'pquiibbmlj'"}], "start": 1734183810137, "stop": 1734183810273}], "parameters": [{"name": "field_name", "value": "'login'"}], "start": 1734183810137, "stop": 1734183810273, "uuid": "70aca9c5-531e-4b96-b51a-0708250cc2bc", "historyId": "216dbf30c18cdf0824f3566d9890db31", "testCaseId": "e19d5f6ce864d2e906838d7c7da07064", "fullName": "tests.tests_courier.test_courier_login.TestLoginCourier#test_login_courier_with_incorrect_login_or_password", "labels": [{"name": "parentSuite", "value": "tests.tests_courier"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "172.31.52.44-vpn.dhcp.yndx.net"}, {"name": "thread", "value": "18169-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_courier.test_courier_login"}]}